### PR TITLE
Fix build and demo

### PR DESCRIPTION
**Pull request by timleland**
@acstech/doppler-maintainers 

Give this a try. Make sure you **npm install**

### CODE REVIEW

**Comment by pjkaufman** [comment]
I tried from my normal Windows computer after installing, node.js, vue.js, and npm, but it was unsuccessful. Here is the error message:

Module build failed: Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (C:\Users\topse\Documents\gitrepos\doppler-frontend\node_modules\eslint\lib\config.js:255:39)
    at Config.getConfigHierarchy (C:\Users\topse\Documents\gitrepos\doppler-frontend\node_modules\eslint\lib\config.js:179:43)
    at Config.getConfigVector (C:\Users\topse\Documents\gitrepos\doppler-frontend\node_modules\eslint\lib\config.js:286:21)
    at Config.getConfig (C:\Users\topse\Documents\gitrepos\doppler-frontend\node_modules\eslint\lib\config.js:329:29)
    at processText (C:\Users\topse\Documents\gitrepos\doppler-frontend\node_modules\eslint\lib\cli-engine.js:163:33)
    at CLIEngine.executeOnText (C:\Users\topse\Documents\gitrepos\doppler-frontend\node_modules\eslint\lib\cli-engine.js:620:17)
    at lint (C:\Users\topse\Documents\gitrepos\doppler-frontend\node_modules\eslint-loader\index.js:229:17)
    at transform (C:\Users\topse\Documents\gitrepos\doppler-frontend\node_modules\eslint-loader\index.js:212:18)
    at C:\Users\topse\Documents\gitrepos\doppler-frontend\node_modules\loader-fs-cache\index.js:127:18
    at ReadFileContext.callback (C:\Users\topse\Documents\gitrepos\doppler-frontend\node_modules\loader-fs-cache\index.js:31:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

Granted, this error maybe due to the different operating systems.

**Comment by pjkaufman** [comment]
Are all the files with a dot being copied?
I ask becuase that seems to be an issue that causes this according to https://discourse.roots.io/t/sage-9-module-build-failed-error-no-eslint-configuration-found/7635.

**Comment by pjkaufman** [comment]
I'm downloadin the repo as a zip file since trying to clone the repo is just allowing me to look at a master branch.

**Comment by pjkaufman** [comment]
Downloading the zip fixed the eslint issue.

**Comment by timleland** [comment]
image

Try changing the branch in the dropdown

**Pull request merged**
